# Generated by Django 3.2.16 on 2022-12-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_resevanjeeksponentneenacbe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplosniClenAritmeticnegaZaporedja',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
                ('od', models.IntegerField(default=-5, verbose_name='Od')),
                ('do', models.IntegerField(default=5, verbose_name='Do')),
            ],
            bases=('problems.problem',),
        ),
    ]
