# Generated by Django 3.2.16 on 2022-12-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_splosniclenaritmeticnegazaporedja'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplosniClenAritmeticnegaEnacbi',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
            ],
            options={
                'verbose_name': 'Zaporedja / splošni člen aritmetičnega zaporedja iz enačb',
            },
            bases=('problems.problem',),
        ),
        migrations.AlterModelOptions(
            name='splosniclenaritmeticnegazaporedja',
            options={'verbose_name': 'Zaporedja / splošni člen aritmetičnega zaporedja'},
        ),
    ]
